### ISSUE TITLE
There should be a way to do a "silent install" on Windows

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-desktop#104]
### Expected Behavior

The application should be able to be installed from the command line with a flag to make it install without user input.  This can help mass installs and ensuring that many machines get the same settings for network administrators.

### Actual Behavior

There's no way to do it now.  @cwillisf said: NSIS (the installer system we're using) normally supports /s for a silent install but it doesn't seem to work with ours.

### Operating System and Browser

Windows

**Comment by cwillisf** [comment]
Turns out that using `/S` works -- it must be a capital S. Along with that, you can choose `/currentuser` or `/allusers` to determine the installation context.

Silent install for current user:
```
/S /currentuser
```

Silent install for all users (requires administrator privileges):
```
/S /allusers
```
