### ISSUE TITLE
Existing projects not saving

### ISSUE THREAD

**Issue by SteveDoesStuff** [LLK/scratch-desktop#107]
### Expected Behavior

After making changes to a previously saved project, resaving and choosing to replace the file should properly replace it with the current version.

### Actual Behavior

After making changes to a previously saved project, resaving and choosing to replace the file does not update the save file at all, and closing Scratch will lose any changes made. Saving with a new filename works as expected, but for some reason Scratch is not writing changes to existing files.

### Steps to Reproduce

1. Load an existing project (or quickly make a new one and save it with a filename that is not already taken)
1. Make a change to the project such as adding a block or changing a parameter on a used block
1. Save the project using the same filename and accept the OS prompt to replace the file
1. Quit Scratch
1. Relaunch Scratch and re-load the same project

### Operating System and Browser

Mac OS 10.15.3 - Scratch Desktop 3.6.0 (from App Store)

**Comment by Geoffrey42** [comment]
+1 to this. I am experimenting the same issue on Mac OS Catalina with the App Store application.

**Comment by apple502j** [comment]
Cannot repro on Windows 10, exe version (3.9). Gonna try app store version(3.6)

**Comment by apple502j** [comment]
Also, did you make sure you didn't double-click to save?

**Comment by johannrichard** [comment]
Kids here experienced the same problem and lost changes to their projects. I did some more testing between AppStore Version and Direct Download from MIT Website:

* **Same problem** here on MacOS Catalina 10.15.3, with Scratch Desktop 3.6.0 **from the AppStore**
* **No problem** with Scratch 3.6.0 **directly downloaded from MIT Website**

**Comment by johannrichard** [comment]
Just another comment: I was wondering whether the App Store version would need to request appropriate permissions (Files & Folder permissions) due to recent changes in Catalina. 

To be noted that even when giving *Full Disk Access*  to Scratch Desktop (AppStore Version), the problem persists, irrespective whether the file is saved under a user's Documents/Desktop or elsewhere (e.g. Downloads folder or something else).

**Comment by apple502j** [comment]
@cwillisf critical bug (data loss). probably something in https://github.com/LLK/scratch-desktop/blob/develop/buildResources/entitlements.mas.plist

**Comment by BryceLTaylor** [comment]
I've finally been able to reproduce this issue.  It turns out it is only happening with the Mac App store build.  The direct download version works just fine.  This confirms what @johannrichard said above.

**Comment by cwillisf** [comment]
I believe this is related to electron/electron#10950
I'm still trying to figure out how to fix it... adding the `downloads.read-write` entitlement (as suggested in that issue) fixes the problem if the save is going to the "Downloads" folder, but not anywhere else. I suspect the "app-scoped security bookmarks" path is the right way to fix this.
