### ISSUE TITLE
Camera and microphone not working on macOS

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-desktop#109]
### Expected Behavior

Attempting to use the video sensing extension or sound recorder should, on macOS 10.14 and higher:
- Request permission to use the camera/microphone (at least the first time)
- Cause the application to appear in the Camera or Microphone section of "Security & Privacy" in System Preferences
- Function correctly in the application

### Actual Behavior

On macOS 10.14.6, none of the above items are true.

### Steps to Reproduce

Camera:
1. Run Scratch Desktop 3.9.0 or higher
2. Add the "Video Sensing" extension
3. Look at the stage

Microphone:
1. Run Scratch Desktop 3.9.0 or higher
2. Go to the "Sounds" tab and activate the sound recorder
3. Note that the loudness indicator does not correctly respond to noise
4. Press "Record"
5. Note that only silence is recorded

### Operating System and Browser

macOS 10.14.6
Scratch Desktop 3.9.0 (Electron 6.1.7, Chrome 76.0.3809.146)

**Comment by apple502j** [comment]
Useful information: https://www.electronjs.org/docs/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos

**Comment by cwillisf** [comment]
Testing note: as far as I can tell, once an application has been granted (or denied) permission to use the camera or microphone there's no way to make the application ask again other than to reset the permission list entirely. You can do that with `tccutil` like this:
```
tccutil reset Camera
tccutil reset Microphone
```
