### ISSUE TITLE
Scratch Desktop can't be used on 32bit Windows

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-desktop#114]
A Scratcher Little-Earthworm reported that Scratch Desktop 3.9.0 can't be used on 32bit Windows: https://scratch.mit.edu/discuss/post/3919819/ and also said 3.6.0 works.

This change is (probably) due to a 3.7.0(unreleased) commit https://github.com/LLK/scratch-desktop/commit/d077e79a8a300b23e4074c66af7d9af14f554444 - we need to have `nsis:ia32` instead of `nsis`. (Because of WOW64 it should work fine on 64-bit OS but if not, we can have 2 downloads)

**Comment by tailindu** [comment]
Can Scratch Desktop be used on   64bit Windows?

**Comment by lishinian** [comment]
I compiled the 32-bit version and uploaded to my own website.
https://www.bunnyzoo.com/download.html#scratchbox

Enjoy it~ : )

**Comment by tailindu** [comment]
> I compiled the 32-bit version and uploaded to my own website.
> https://www.bunnyzoo.com/download.html#scratchbox
> 
> Enjoy it~ : )

so thank you .i have installed it ,while that is not what i want.i want  the " ftscratch3 desktop"(which is different from  scratch desktop ) , combined Fischer with scratch3.0

**Comment by lishinian** [comment]
> ftscratch3

well,  i found ftscratch3's github repo. i will try to compile  the 32-bit version for U.

Hold the line~

**Comment by tailindu** [comment]
> > ftscratch3
> 
> well, i found ftscratch3's github repo. i will try to compile the 32-bit version for U.
> 
> Hold the line~

All the time~~Thank you.I find your ID name"lishinan" seems like a chinese name,can you speak chinese?(再次由衷感谢你的帮助)

**Comment by lishinian** [comment]
> > > ftscratch3
> > 
> > 
> > well, i found ftscratch3's github repo. i will try to compile the 32-bit version for U.
> > Hold the line~
> 
> All the time~~Thank you.I find your ID name"lishinan" seems like a chinese name,can you speak chinese?(再次由衷感谢你的帮助)

哈哈  那就用中文交流吧   我发现ftscratch3只是一个公司的产品  我不确定他们是否让我这样做

其实编译十分简单  把build的shell里面--arch=x64改成--arch=ia32即可

**Comment by tailindu** [comment]
> > > > ftscratch3
> > > 
> > > 
> > > well, i found ftscratch3's github repo. i will try to compile the 32-bit version for U.
> > > Hold the line~
> > 
> > 
> > All the time~~Thank you.I find your ID name"lishinan" seems like a chinese name,can you speak chinese?(再次由衷感谢你的帮助)
> 
> 哈哈 那就用中文交流吧 我发现ftscratch3只是一个公司的产品 我不确定他们是否让我这样做
> 
> 其实编译十分简单 把build的shell里面--arch=x64改成--arch=ia32即可

就是我们德国总部的产品，我们在国内现在要登录网站，打开网页使用，经常出现打不开网页情况。所以我们想把它做成桌面版的，或者放到国内自己服务器上。德国那边也给出了办法，我照着操作，安装失败.多少位的系统其实都不是最重要的。

**Comment by tailindu** [comment]
> > > > > ftscratch3
> > > > 
> > > > 
> > > > well, i found ftscratch3's github repo. i will try to compile the 32-bit version for U.
> > > > Hold the line~
> > > 
> > > 
> > > All the time~~Thank you.I find your ID name"lishinan" seems like a chinese name,can you speak chinese?(再次由衷感谢你的帮助)
> > 
> > 
> > 哈哈 那就用中文交流吧 我发现ftscratch3只是一个公司的产品 我不确定他们是否让我这样做
> > 其实编译十分简单 把build的shell里面--arch=x64改成--arch=ia32即可
> 
> 就是我们德国总部的产品，我们在国内现在要登录网站，打开网页使用，经常出现打不开网页情况。所以我们想把它做成桌面版的，或者放到国内自己服务器上。德国那边也给出了办法，我照着操作，安装失败.多少位的系统其实都不是最重要的。

要不加个扣扣吧，1012157429

**Comment by lishinian** [comment]
> > > > > > ftscratch3
> > > > > 
> > > > > 
> > > > > well, i found ftscratch3's github repo. i will try to compile the 32-bit version for U.
> > > > > Hold the line~
> > > > 
> > > > 
> > > > All the time~~Thank you.I find your ID name"lishinan" seems like a chinese name,can you speak chinese?(再次由衷感谢你的帮助)
> > > 
> > > 
> > > 哈哈 那就用中文交流吧 我发现ftscratch3只是一个公司的产品 我不确定他们是否让我这样做
> > > 其实编译十分简单 把build的shell里面--arch=x64改成--arch=ia32即可
> > 
> > 
> > 就是我们德国总部的产品，我们在国内现在要登录网站，打开网页使用，经常出现打不开网页情况。所以我们想把它做成桌面版的，或者放到国内自己服务器上。德国那边也给出了办法，我照着操作，安装失败.多少位的系统其实都不是最重要的。
> 
> 要不加个扣扣吧，1012157429

已经加了  不过貌似没有通过

**Comment by apple502j** [comment]
Reported on the forum again: https://scratch.mit.edu/discuss/post/4060658/
@cwillisf @BryceLTaylor  I think this is High/Medium impact
