### ISSUE TITLE
macOS App Store is not updated

### ISSUE THREAD

**Issue by lvjp** [LLK/scratch-desktop#115]
The macOS App Store version is 3.6.0 but the 3.10.2 is already packaged.

Can you update more frequently App Store ?

**Comment by BryceLTaylor** [comment]
Thanks for your question.  We know that the app store is behind the direct download version.  We've had some trouble with their review process, but didn't want Scratch Desktop to get completely behind what is available online, so we have continued to update the direct download version.  Sorry for any inconvenience.
