### ISSUE TITLE
Scratch Desktop - Application helper uses a lot of memory (Only checked on Mac)

### ISSUE THREAD

**Issue by redstone-dev** [LLK/scratch-desktop#122]
### Expected Behavior

Scratch Desktop should not freeze up.

### Actual Behavior

Scratch Desktop sometimes freezes up and gets stuck. In severe cases it can even become just a blank white window.

This may seem like it happens randomly, but if you look in Activity Monitor

### Steps to Reproduce (Mac Only)
1. Press Cmd-Space and type in **Activity Monitor**.
![Step 1](https://user-images.githubusercontent.com/31410740/83695989-4d2c9b80-a5c9-11ea-983a-0adea4b8df2f.gif)

2. Fire up **Scratch Desktop**.
![Step 2](https://user-images.githubusercontent.com/31410740/83697057-f5dbfa80-a5cb-11ea-8cb4-cb9f68a6e13b.gif)

3. Notice the **Scratch Desktop Helper**'s high memory usage.
![Screen Shot 2020-06-03 at 17 51 48](https://user-images.githubusercontent.com/31410740/83697159-4c493900-a5cc-11ea-8e1d-ef50807cda80.png)

### Operating System and Browser

Mac OS 10.14.6, Chrome 83.0.4103.61 on MacBook Air 2017 (I think)

**Comment by BryceLTaylor** [comment]
@redstone2010 If the file is too large, could you upload it to the Scratch website and share a link to it?

**Comment by redstone-dev** [comment]
> @redstone2010 If the file is too large, could you upload it to the Scratch website and share a link to it?

Maybe. I'll see though, since the file was so large that I had to import it in Scratch Desktop.

**Comment by ecc521** [comment]
If the scratch helper is running 630MB, what's the total memory usage? Opening up a larger project like Generic Red (https://scratch.mit.edu/projects/292297781/) uses a solid 250MB in browser, and Electron can easily run 200MB on it's own. If the project you are using is too large for the scratch website, I suspect this isn't actually an issue with the app.

**Comment by redstone-dev** [comment]
@ecc521 Hm, maybe.

**Comment by BryceLTaylor** [comment]
I'm going to close this issue since I believe the impact is extremely low.
