### ISSUE TITLE
Application name should be "Scratch"

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-desktop#126]
### Expected Behavior

After some discussion we have concluded that the name "Scratch Desktop" can be confusing for users and isn't as searchable as we'd like. We've concluded that the application should be called "Scratch" instead. We'd also like to display the version number in the title bar when the app is running, like "Scratch 3.13.0" for example.

### Actual Behavior

The application is currently called "Scratch Desktop" and displays "Scratch Desktop" in the title bar when the app is running.

**Comment by apple502j** [comment]
I'm slightly worried that if the app name is Scratch, on Windows it will be installed to `C:\Program Files (x86)\Scratch`, which overrides Scratch 1.4 installation.

**Comment by cwillisf** [comment]
@apple502j yeah - there's a similar problem on macOS, with `/Applications/Scratch.app`, and even if the directory is different it might be confusing to have two "Scratch" results when searching (for example) the Start Menu.

We talked about these issues on the Scratch team and decided that it's mostly advanced users who might have both Scratch 1.4 and 3.0 installed simultaneously, and in general reducing newcomers' confusion about whether "Scratch Desktop" is or isn't Scratch is a higher priority. More advanced users, such as yourself, will probably notice the difference in the icon for example, and can rename the installation directory to avoid the conflict.

I don't think there's a single solution that solves all of these problems, but we'll try to solve as many as we can.

**Comment by apple502j** [comment]
Can't we name it "Scratch 3.0"?

**Comment by cwillisf** [comment]
The title of this issue is a little bit oversimplified... there are actually several things that we're looking at, including:
- the directory name of the application
- the file name of the application
- the name of the item in the stores (Mac App Store / Microsoft Store)
- the name we use to refer to the application in documentation or on the Scratch website
- the text appearing as the title when the application is running
- probably I'm forgetting about at least one or two more ;)

Some of these depend on others, depending on the operating system.

Our current plan is to use "Scratch 3.0" and "Scratch" for most of these, but not "Scratch Desktop" for any of them (any more), and a few of them will be a little more customized. For example, we're planning on showing the exact version number in the application title when it's running.
