### ISSUE TITLE
"open" menu does not show .sb, .sb2, or .sb3 files on Windows

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-desktop#14]
The first time I clicked "File>Load from your computer", the file browser was on the downloads folder and it didn't show me any .sb, .sb2, or .sb3 files.  I had previously just saved a project from Scratch Desktop to the downloads folder.

I switched to "All Files" and could see the file I knew was there.  The next time I opened it and chose "Custom Files" rather than "All Files", .sb3 files were visible.

This may be the application or operating system learning to associate .sb3 files with Scratch Desktop.  It doesn't seem to be the default.

### Steps to Reproduce
Download or save an .sb3 onto your computer and note where you saved it
Having never opened an .sb3 file on the computer, click File>Load from your computer
Navigate to wherever the saved .sb3 file is
Note: With "Custom Files" chosen the .sb3 does not appear in the list of files.

### Operating System
Windows

**Comment by thisandagain** [comment]
We are getting lots of reports from users on Windows that they are having trouble opening projects. I *believe* this issue is the root cause, but we should discuss. Scheduling this as "critical" for August.

**Comment by apple502j** [comment]
May have something to do with:
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ComDlg32\OpenSavePidlMRU`
![image](https://user-images.githubusercontent.com/33279053/62096469-bca57080-b2be-11e9-83df-d7cc93996537.png)

**Comment by cwillisf** [comment]
Has there been enough time to tell if you've seen a change in the rate of reports of this kind of problem since the launch of 3.5.0? I'll try a few more things to repro but currently I don't see anything that seems like it could cause this. It does seem like #32 could be seen as "trouble opening projects" though.

**Comment by BryceLTaylor** [comment]
I think most of the issues about opening projects are from #32 lately.  I'm going to close this, since I haven't heard reports of this in a while.
