### ISSUE TITLE
All extensions are now running with 'use strict' ?

### ISSUE THREAD

**Issue by chrisruk** [LLK/scratch-desktop#152]
### Actual Behaviour

With the following code in an extension: 

```
    for (count = 0; count < 64; count++){
    }
```

I get:

```
Uncaught ReferenceError: count is not defined
````
Would I be right in thinking all extensions are now running as 'use strict'?, as I notice I can fix this by doing:

```
    for (let count = 0; count < 64; count++){
    }
```

This appears to be a recent change, as in branches 3.12, the code 'for (count = 0; count < 64; count++){' worked without exception.

### Operating System and Browser

Linux

**Comment by cwillisf** [comment]
Hmm... I'm not aware of an intentional change that should have done this, but I'm inclined to think that strict mode is a good idea anyway. Is this a problem for your use-case?

**Comment by chrisruk** [comment]
No, it's not a problem, I have now made the changes to the extensions so that they function ok.  And I agree it does seem a good idea.

Was curious if 'use strict' was being added somewhere for the extensions being loaded as the behaviour seemed to change for me, maybe something changed with an external library though.

Thanks again, will close this now.

**Comment by cwillisf** [comment]
No worries - I'm curious where this is coming from too. While I'm OK with extensions running in strict mode, I'm somewhat less OK with this being a surprise change. I'll admit that figuring out isn't a top priority, but if you (or anyone) figures out where this came from I'd love to hear about it!
