### ISSUE TITLE
My own app reinstalls the original Scratch Desktop

### ISSUE THREAD

**Issue by mkovalevski** [LLK/scratch-desktop#163]
Hello! My own app with some extensions deletes the original Scratch Desktop and then installs my app based on scratch-desktop. I want those two apps be installed on my computer. I generated NSIS installer for Windows 10. Does anybody know how to fix it and make those two apps, mine and original, work together on Windows OS?

**Comment by cwillisf** [comment]
Hmm... this really depends on how you have NSIS set up in your project. My recommendation is to look through your configuration settings for any identifiers such as `scratch-desktop` (especially `edu.mit.scratch.scratch-desktop`) or any unique ID numbers (look like `XXXXXXXX-XXXX-XXXX-XXXXXXXXXXXX`) and make sure you've replaced those values with your own.

If that doesn't help I'd recommend reading more about NSIS configuration or asking this question in a place that offers NSIS support. Good luck!

**Comment by mkovalevski** [comment]
@cwillisf Thank u very much! It worked.
