### ISSUE TITLE
"npm start" got error!

### ISSUE THREAD

**Issue by mkygogo** [LLK/scratch-desktop#164]
### When I run "npm start" got error like this :

` ERROR in ./node_modules/scratch-vm/src/virtual-machine.js
  Module not found: Error: Can't resolve 'scratch-parser' in 'E:\steam\scratch\scratch_git\scratch3\scratch-desktop\node_modules\scratch-vm\src'
   @ ./node_modules/scratch-vm/src/virtual-machine.js 331:23-48 604:23-48
   @ ./node_modules/scratch-vm/src/index.js
   @ ./src/renderer/app.jsx
   @ ./src/renderer/index.js
   @ multi css-hot-loader/hotModuleReplacement ./src/renderer/index.js

  ERROR in ./node_modules/scratch-vm/src/virtual-machine.js
  Module not found: Error: Can't resolve 'scratch-sb1-converter' in 'E:\steam\scratch\scratch_git\scratch3\scratch-desktop\node_modules\scratch-vm\src'
   @ ./node_modules/scratch-vm/src/virtual-machine.js 343:10-42
   @ ./node_modules/scratch-vm/src/index.js
   @ ./src/renderer/app.jsx
   @ ./src/renderer/index.js
   @ multi css-hot-loader/hotModuleReplacement ./src/renderer/index.js`

### Operating System and Browser

windows 8

**Comment by onlycs** [comment]
Run `npm install` first.
