### ISSUE TITLE
The option to sign in isn't showing up at all its just blank in the corner

### ISSUE THREAD

**Issue by uglydumping** [LLK/scratch-desktop#177]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by BryceLTaylor** [comment]
@uglydumping please provide the information requested in the template when opening an issue.
