### ISSUE TITLE
Scratch Desktop should not display the preview modal

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-desktop#2]
The offline editor should not ask you if you want to try 3.0, nor ask you to load a 2.0 project by id.

This should not be there:
![screen shot 2018-12-10 at 4 51 55 pm](https://user-images.githubusercontent.com/1088291/49763908-f11adc80-fc9b-11e8-818c-5196e80a09e4.png)

### Steps to reproduce
Launch the offline editor
Note: there is a modal asking you to try 

### Operating System:
Mac and Windows

**Comment by cwillisf** [comment]
Scratch Desktop updated to a post-preview version of the GUI a while ago, so this is no longer an issue.
