### ISSUE TITLE
error on command: npm start

### ISSUE THREAD

**Issue by ffsher** [LLK/scratch-desktop#200]
Hi All,

I am new to study and every thing is fine til command: "npm start" ,when I followed steps detailed on _scratch-desktop README.md_.

### Actual Behavior
ffsher@DESKTOP-OAHCTK8:/mnt/c/Scratch_build/scratch2exe/zip/scratch-desktop$ **sudo npm start**
[sudo] password for ffsher:

> scratch-desktop@3.24.0 start /mnt/c/Scratch_build/scratch2exe/zip/scratch-desktop
> mkdirp ./dist && electron-webpack dev --bail --display-error-details --env.minify=false --no-progress

[1457:0712/153004.645918:FATAL:electron_main_delegate.cc(211)] **Running as root without --no-sandbox is not supported**. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)
Error: Command failed: /mnt/c/Scratch_build/scratch2exe/zip/scratch-desktop/node_modules/electron/dist/**electron --version**
[1457:0712/153004.645918:FATAL:electron_main_delegate.cc(211)] **Running as root without --no-sandbox is not supported**. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)
...........

### What I work on this issue

I do some research 
https://stackoverflow.com/questions/59203085/fatal-running-as-root-without-no-sandbox-is-not-supported-using-electron-7-1
And seems to **electron**.

As attached link, addition of parameter "--no-sandbox" is workaround.

But, where is the position i can put the parameter? 
Or, any other suggestion to pass the error

### Operating System and Browser
version 
Ubuntu 16.04.7 LTS
npm : 6.14.13
electron : v8.5.5
node : v14.17.2

thanks for you advise.

**Comment by apple502j** [comment]
Can't you remove the sudo?

**Comment by ffsher** [comment]
Hi apple502j,

thanks for you reply.

command : npm start(without sudo). 
I tried before and had other error. 

By studying on website, i found this is **electron** hot issue.

I still keep debugging this error. if any good news, i would post on this section

**Comment by rschamp** [comment]
You shouldn't run `npm` commands with `sudo`. If you have a different issue running the command without `sudo`  please open a new issue with that.

**Comment by ffsher** [comment]
Yes, i remove sudo from npm. but, procedure still has error.

Actually, i use WSL and got some idea by the link : 
https://stackoverflow.com/questions/63784533/cant-run-electron-on-win10-ubuntu-subsystem

 WSL need to be switched "metadata"
