### ISSUE TITLE
Basic clone, pull, push Git integration in a kid friendly way

### ISSUE THREAD

**Issue by eduardo-lago-aguilar** [LLK/scratch-desktop#204]
### Expected Behavior

The Scratch Editor should be able to

- initialize a git repository in the project
- or open a local/remote git project fetching the changes
- pull and push the changes in a friendly way (like a sync button)
- all changes performed in the master branch (another issue to change branches and perform other operations)

### Actual Behavior

- there is no git integration

### Steps to Reproduce

- open Scratch Editor, there is not git integration at all

### Operating System and Browser

- All OS supported

**Comment by apple502j** [comment]
Scratch project is not very Git-friendly. The code is stored as one big file and merging or conflict solving is... a hell. Not to mention the fact the files are minified to save disk space.

**Comment by BryceLTaylor** [comment]
Thanks for the suggestion, but we are not going to implement this feature.
