### ISSUE TITLE
Upgrade to Electron 13 in order to support Debian Bullseye

### ISSUE THREAD

**Issue by grega** [LLK/scratch-desktop#205]
Due to a sandboxing issue in Chromium ([layer-2 seccomp-bpf sandbox](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux/sandboxing.md#The-sandbox-1)), older versions of Electron do not run on Debian Bullseye without setting the `--disable-seccomp-filter-sandbox` flag.

The sandboxing issue has been [recently fixed](https://chromium-review.googlesource.com/c/chromium/src/+/2785131) and available since Chromium 91.0.4459.0.

Chromium 91 (specifically >91.0.4459.0) is supported in [Electron 13.0.0](https://github.com/electron/electron/releases/tag/v13.0.0) and above, so it'd be really helpful to see scratch-desktop run on Electron 13 in order to package it up for Bullseye (in particular, for the Bullseye version of Raspberry Pi OS).

Is there a particular reason that scratch-desktop is pinned to Electron 8.2.5? (there's a [PR](https://github.com/LLK/scratch-desktop/pull/180) with a bump to Electron 11.0.2 so am somewhat assuming not)

**Comment by kccuber-scratch** [comment]
resolved. electron's at ^15.3.1 now.
https://github.com/LLK/scratch-desktop/blob/5b0c63ba9474464ffec99fb5dcd6b544da786aba/package.json#L42
