### ISSUE TITLE
Can't save project anymore on Linux platform since upgrade to Electron 15

### ISSUE THREAD

**Issue by et451** [LLK/scratch-desktop#213]
### Expected Behavior

When I want to save a project in Scratch-Desktop, I click on ` File > Save to your computer `.
A save file dialog box should open in order to choose a folder and a file name.

### Actual Behavior

Nothing happens, the save file dialog box doesn't show anymore.

If Scratch-Desktop is started from a console, there is a message error:
`Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed`

### Steps to Reproduce

1. Start Scratch-desktop
2. Click on ` File > Save to your computer `

### System Details

Platform: Linux (Arch Linux x64)
DE: Plasma KDE
Scratch-Desktop: 3.27.0 built with last package.json update (with Electron 15.3.1)

Seems to be an Electron bug that only affects Linux platform:
https://github.com/electron/electron/issues/31152

When the application is built with Electron 13.6.2, everything works correctly.

**Comment by kchadha** [comment]
We don't officially support Linux and this seems to be a bug within Electron itself, so hopefully will get fixed in an update there.

**Comment by sphaero** [comment]
Just ran this repo from scratch and it runs fine and also is able to save projects
