### ISSUE TITLE
Make it possible to see which version of Scratch Desktop app I'm running

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-desktop#23]
In Mac, I'd like to be able to see which version of the Scratch Desktop app I'm running.

Maybe we could make a menu item like `File->Version 1.2.0` (wouldn't even have to do anything!)

Or, some kind of more elaborate "About Scratch Desktop" item?

**Comment by ntlrsk** [comment]
+1 The ability to easily see which Scratch Desktop version is running was just requested by Ade who organizes Africa Code Week in many different countries.

**Comment by thisandagain** [comment]
@ntlrsk Noted! Added to @cwillisf plate for after he gets through a few high-priority items we have in process right now.

**Comment by ntlrsk** [comment]
Just adding that Ade who organizes Africa Code Week in SAP said yesterday this would be extremely helpful if possible to add for August update as he tries to support the Africa Code Week ambassadors.
