### ISSUE TITLE
Installer should include an Install per-machine rather than per-user option

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-desktop#36]
Currently when you install Scratch-Desktop on Windows it only installs on one user's account.  There should be an option to install for the whole machine so any user can access the program.

### Details
From a fresh desk ticket:
"...And it does not help that the current installer installs to "APP Data" in individual user profiles, meaning of course it needs to be installed every time a different user logs on to a computer."

Related to #35 

### Operating System
Windows

**Comment by cwillisf** [comment]
Fixed by 1de581d01d7148f8dc89ea65d17298523692edc0
