### ISSUE TITLE
Does it work for linux?

### ISSUE THREAD

**Issue by ghirardinicola** [LLK/scratch-desktop#37]
If yes, i think it should be mentioned somewhere.
Thanks

**Comment by thisandagain** [comment]
We currently do not support running Scratch Desktop on Linux.

**Comment by mikebarkmin** [comment]
I have build an AppImage based on this repository (no modifications needed) and it runs great on Ubuntu 18.04. See https://github.com/mikebarkmin/scratch-desktop/releases/download/1.2.1/ScratchDesktop-1.2.1.AppImage

**Comment by towerofnix** [comment]
Yes, do note that while the Scratch Team is not explicitly supporting nor targeting Linux, at least at present moment scratch-desktop does build and run excellently on Linux (in addition to Ubuntu as above, I've tried on Debian).
