### ISSUE TITLE
Make a packaged build error

### ISSUE THREAD

**Issue by zhengyongxiong** [LLK/scratch-desktop#38]
I followed the steps to this point.
npm run dist
![image](https://user-images.githubusercontent.com/13392637/55204354-9e910c00-5209-11e9-9167-3923e8a9c020.png)
![image](https://user-images.githubusercontent.com/13392637/55204376-b7012680-5209-11e9-8db2-bb6041327bb7.png)
![image](https://user-images.githubusercontent.com/13392637/55204394-c4b6ac00-5209-11e9-96c1-8c3f1c064dec.png)
Have you ever encountered this problem? How to solve it?

**Comment by towerofnix** [comment]
Just to be certain, did you closely follow [the "Prepare `scratch-gui`" section](https://github.com/LLK/scratch-desktop#prepare-scratch-gui)? There should be a folder `G:\scratch3.0\scratch-desktop\node_modules\scratch-gui`. If that folder doesn't exist, you should follow those steps again, just in case you accidentally forgot to do one of the steps earlier (or something similar).

**Comment by zhengyongxiong** [comment]
![image](https://user-images.githubusercontent.com/13392637/55207716-54625780-5216-11e9-8f16-df7d0c022a48.png)
This directory exists.

**Comment by zhengyongxiong** [comment]
Is there an error in this catalogue?

**Comment by cwillisf** [comment]
@zhengyongxiong it looks like you might have skipped some of the steps in [the "Prepare `scratch-gui`" section](https://github.com/LLK/scratch-desktop#prepare-scratch-gui) that @towerofnix mentioned, especially step 3 and maybe step 2 also. It should be safe to do steps 2 and 3 more than once, so I would suggest doing them both now just to be sure.

**Comment by zhengyongxiong** [comment]
> @zhengyongxiong it looks like you might have skipped some of the steps in [the "Prepare `scratch-gui`" section](https://github.com/LLK/scratch-desktop#prepare-scratch-gui) that @towerofnix mentioned, especially step 3 and maybe step 2 also. It should be safe to do steps 2 and 3 more than once, so I would suggest doing them both now just to be sure.

Do you have any detailed procedures?

**Comment by cwillisf** [comment]
The instructions are here: https://github.com/LLK/scratch-desktop#prepare-scratch-gui
