### ISSUE TITLE
Build error on CentOS Linux

### ISSUE THREAD

**Issue by zhengyongxiong** [LLK/scratch-desktop#40]
Make a packaged build  erro!
Have you ever had such a problem? How to solve it?
![image](https://user-images.githubusercontent.com/13392637/55445550-7da42e80-55ee-11e9-866f-224d5e9ec552.png)
![image](https://user-images.githubusercontent.com/13392637/55445561-88f75a00-55ee-11e9-955f-6da07970e0b8.png)

**Comment by towerofnix** [comment]
Looks like scratch-desktop requires libgtk to install. Depending on what Linux distro you use, you can probably install that with `apt`/`apt-get`.

**Comment by zhengyongxiong** [comment]
centos linux

**Comment by cwillisf** [comment]
Though in some cases it might build and work correctly, we don't officially support Scratch Desktop in Linux. See also: #37
