### ISSUE TITLE
No NPM dependencies installed

### ISSUE THREAD

**Issue by CmdrNorthpaw** [LLK/scratch-desktop#43]
I've been building this app for myself (for learning), but every time I run BUILD_MODE=dist npm run build it throws another missing package error (I must have installed hundreds of packages in this way). Is there anything I can do to install all the dependencies at once?

**Comment by cwillisf** [comment]
Please follow the instructions here: https://github.com/LLK/scratch-gui#getting-another-repo-to-point-to-this-code

Remember to use the `scratch-desktop` branch or `scratch-gui` instead of the default `develop` branch.
