### ISSUE TITLE
npm run dist erro!

### ISSUE THREAD

**Issue by zhengyongxiong** [LLK/scratch-desktop#44]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/13392637/56120137-24e67580-5fa0-11e9-8d92-56584642d5c0.png">
I run "nom run diet "on my MacBook,have a error!
everybody know what that is?

**Comment by cwillisf** [comment]
Building `dist` on macOS requires developer certificates. If you haven't signed up for a macOS developer account and installed the relevant certificates you'll be able to debug but you won't be able to build packages.
