### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by iamsush** [LLK/scratch-desktop#45]
I followed the doc and tried to run scratch-desktop,
even [the "Prepare scratch-gui" section](https://github.com/LLK/scratch-desktop#prepare-scratch-gui)

Steps after preparing scratch-gui: 
```
npm install
npm start
```

But still I am getting the below error,

![2019-04-26 at 15-55-49](https://user-images.githubusercontent.com/17278151/56801919-4d8e2b00-683c-11e9-9e50-91ed80cc478a.png)

I checked node_modules folder, scratch-gui is there but I am not sure why I am getting the above error.

----------
Machine: Windows 10 x64

**Comment by dlech** [comment]
I had the same problem. Then I found the missing steps at https://github.com/LLK/scratch-gui#developing-alongside-other-scratch-repositories

You also have to run `npm link` in the scratch-gui folder and then `npm link scratch-gui` in the scratch-desktop folder.

**Comment by iamsush** [comment]
Thanks, that worked out for me too. But I have one more doubt, how can we get hot reloading with the scratch-gui when used with scratch-desktop. As, I am unable to do it. The application (scratch-desktop) doesn't hot reload when changes are made in scratch-gui (npm link is done).

**Comment by PeaceInDream** [comment]
you maybe lost one step. In the scratch-gui folder , You also have to run: set BUILD_MODE=dist && npm run build , after all these ,you can continue to run: npm link ……
