### ISSUE TITLE
Scratch Desktop doesn't update itself when patches available

### ISSUE THREAD

**Issue by SteveDoesStuff** [LLK/scratch-desktop#47]
The website now has Scratch Desktop v1.2.1, but the v1.2.0 app I currently have installed didn't notify me of the update. Our organization has it installed on a few hundred laptops, so would like to avoid having to download the full app and replacing it on all of our machines with every update.

**Comment by cwillisf** [comment]
Our current strategy is to rely on the auto-update mechanisms built into the Mac App Store and the Microsoft Store. We release both the Store and direct-download versions at roughly the same time so using the Store versions will allow the individual system(s) to keep the app up to date.

We found with Scratch 2.0 that there are quite a few organizations which use the "offline" editor in situations where the user doesn't have rights to update the application. For those organizations, as well as organizations which want more control over update timing, a self-update mechanism won't work or isn't desirable. In those situations we advise using the direct-download version of Scratch Desktop and pushing updates through network administration tools.

Newer administrative tools might be able to use the Mac App Store / Microsoft Store download with centrally-controlled update cadence to get the best of both worlds.

**Comment by SteveDoesStuff** [comment]
Awesome, thanks for the response on that Chris. I didn't realize Scratch Desktop was on the app stores, so we'll migrate over to installing and updating through that
