### ISSUE TITLE
Failed to npm install

### ISSUE THREAD

**Issue by dawnworld** [LLK/scratch-desktop#75]
npm install was hang on 7zip
```
⸨            ░░░░░░⸩ ⠇ extract:app-builder-bin: sill extract 7zip@0.0.6
```
Mac OSX 10.14.6
npm 6.4.1
node v10.15.3
git lastest commit
```
ommit 9ec118ea483cad0a1e2c811813e3e947e95d5fcb (HEAD -> develop, tag: v3.6.0, origin/develop, origin/HEAD)
Author: Christopher Willis-Ford <cwillisf@media.mit.edu>
Date:   Tue Sep 10 12:46:29 2019 -0700

    3.6.0

commit a013abd92591980cc48ea4eba5730b912343dd04 (tag: v3.6.0-rc.2)
Author: Christopher Willis-Ford <cwillisf@media.mit.edu>
Date:   Thu Sep 5 13:10:17 2019 -0700

    3.6.0-rc.2
```

**Comment by cwillisf** [comment]
Hmm... it looks like this is not a problem with scratch-desktop, but instead it's a problem with NPM on your computer or your network connection. You may need a proxy setting for NPM to work correctly.

See here for more information:
npm/npm#14059

**Comment by sujithsomraaj** [comment]
Hello,

Try to install yarn and run yarn install. It will install all your package.json dependencies. When trying to clone from the repository and install all node modules at one time, you can try this
