### ISSUE TITLE
Error after exporting costume

### ISSUE THREAD

**Issue by ercasta** [LLK/scratch-desktop#80]
After exporting a costume, i get the following error:

Uncaught Exception
TypeError: Cannot set property projectName of null at (...something referring DesktopTelemetry) projectSaveCompleted

The costume is actually exported after I click the "OK" button on the error.

I also noticed that the project name gets overwritten with the exported file name.

Scratch Desktop Version 3.6.0
Electron | 4.2.9
Chrome | 69.0.3497.128

**Comment by apple502j** [comment]
Duplicate of #72 
Fixed in #77

**Comment by kchadha** [comment]
Closing as dupe of #72
