### ISSUE TITLE
Should Scratch Desktop respect the GPU blacklist?

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-desktop#81]
Title says all. Ignoring blacklist will solve the problems about WebGL (in this case, browser can return "WebGL is supported", so it was confusing whether WebGL is really supported), but it's crashy.

**Comment by ecc521** [comment]
How about providing a warning message during startup - something like "Your GPU does not appear to support WebGL. We will try running scratch anyway, but serious bugs and glitches may occur"?

**Comment by BryceLTaylor** [comment]
We recently added support for webGL 2 which may support some of these specific GPUs.  We are going to close this and re-evaluate if this comes up again.
