### ISSUE TITLE
Color number is hard to understand and does not match the wiki article

### ISSUE THREAD

**Issue by cuixiping** [LLK/scratch-desktop#89]
### Expected Behavior

Color value matches the wiki article "[Computer Colors][1]"

### Actual Behavior

Color value is hard to understand and does not match the wiki article "[Computer Colors][1]"

### Operating System and Browser

It has nothing to do with the operating system and browser version.

### Steps to Reproduce

Set pen color to different values and draw.

![Color values](https://user-images.githubusercontent.com/1104492/70018466-2ad9a700-15c1-11ea-8103-32ce8414ec89.png)

Obviously it does not meet the calculation rules described in the wiki article "[Computer Colors][1]":

![image](https://user-images.githubusercontent.com/1104492/70018660-cf5be900-15c1-11ea-9e72-a5f83dc5e1d3.png)

So I don't know what's the formula from RGB color to Scratch color number.

[1]: https://en.scratch-wiki.info/wiki/Computer_Colors

**Comment by apple502j** [comment]
Did you use the one with color picker or number input? IIRC color input one works

**Comment by cuixiping** [comment]
> Did you use the one with color picker or number input? IIRC color input one works

This issue is about number input.

**Comment by cuixiping** [comment]
I reported the issue to scratch-gui [#5324](https://github.com/LLK/scratch-gui/issues/5324). This one should be closed.
