### ISSUE TITLE
Electron call from gui

### ISSUE THREAD

**Issue by caxapexac** [LLK/scratch-desktop#90]
I want to require('electron') in scratch_vm to call main electron process from block logic. But scratch-gui and scratch-vm are devDependencies and not a part of electron (maybe I'm wrong). 

My question is 'how to call child_process from scratch_vm?'

**Comment by caxapexac** [comment]
My aim was to call arduino.exe from scratch-gui/vm

**Comment by apple502j** [comment]
You can modify GUI and VM so that:
- VM emits CONNECT_ARDUINO event
- GUI handles it and does props.onArduinoEvent
- Desktop passes a function to onArduinoEvent

**Comment by caxapexac** [comment]
> You can modify GUI and VM so that:
> 
> * VM emits CONNECT_ARDUINO event
> * GUI handles it and does props.onArduinoEvent
> * Desktop passes a function to onArduinoEvent

Can you give me minimal example emitting code? Didn't work with it
And what is 'props'?

**Comment by apple502j** [comment]
Looking at the code is a good way to learn. For example, ask-and-wait block emits QUESTION event. Search and see how to use it. Also, you should learn a bit of React (including props)

**Comment by caxapexac** [comment]
@apple502j ouf really, thank you)
But do you know QUESTION event handling place in scratch-gui?

**Comment by caxapexac** [comment]
And one more problem - scratch_sensing.js gets runtime in constructor but my code is an extension (without constructor). Then how to get runtime in extension code?

**Comment by apple502j** [comment]
Extension constructor can have runtime argument?
https://github.com/LLK/scratch-vm/blob/develop/src/extensions/scratch3_boost/index.js#L1273

**Comment by caxapexac** [comment]
@apple502j so I have learned basics of electron/react/redux but scratch repos structure is so complicated so I don't see place to handle vm events in gui. 

Sensing blocks  emit SAY and QUESTION events but I don't see it in scratch-gui (ctrl+f didn't help)

**Comment by caxapexac** [comment]
@apple502j I mean, src/containers/stage.jsx on the line 103 but it's in ComponentWillUnmount function. I don't have any idea of what it is and who calls this

**Comment by apple502j** [comment]
Scratch 3.0 is full of React codes. Google componentWillUnmount for what it does.

**Comment by caxapexac** [comment]
@apple502j so I do
`this.runtime.emit('L_EVENT', '*****');`
in the vm/src/extensions/myext/index.js
and
`this.props.vm.on('L_EVENT', this.logfunc);`
in the gui/src/containers/blocks.jsx in ComponentDidMount
and it doesn't work. I really need to understand how do they connect (desktop-gui-vm) because there is no info in the documentation/tutorials about separating react in many repos with devDependencies...

**Comment by apple502j** [comment]
Do you know props? It's super handy. It allows you to pass something to a component - internally or externally. For example, container/gui.jsx has so many props and those are set by external programs (such as `isScratchDesktop` which is set by Scratch Desktop app.jsx) and you can refer it as `this.props.isScratchDesktop` inside that file. (So you can `this.props.vm.on("L_EVENT", this.props.callArduino)` and scratch-desktop app.jsx can pass a function to the props)

**Comment by caxapexac** [comment]
@apple502j but where should I place `this.props.vm.on("L_EVENT", this.props.callArduino)`? In controllers/reducers/index.js?

UPD: or maybe it shold be `this.props.vm.runtime.on()`?

**Comment by apple502j** [comment]
containers/gui.jsx would be fine.

**Comment by caxapexac** [comment]
Finally did it! @apple502j really thank you! I wanna buy you coffee how to pay?

**Comment by caxapexac** [comment]
So problem solved I close it...
