### ISSUE TITLE
Forgot to tag 3.7.0?

### ISSUE THREAD

**Issue by refi64** [LLK/scratch-desktop#91]
I noticed it appears to have been released, but no new tag has been added.

**Comment by apple502j** [comment]
Not released yet, actually. https://downloads.scratch.mit.edu/desktop/Scratch%20Desktop%20Setup%203.7.0.exe is 404

**Comment by refi64** [comment]
Touché, I saw the commit and then the gap and figured it must've been released already. Sorry for the noise.

**Comment by cwillisf** [comment]
No worries - thanks for keeping us honest :D

In case you're curious, the trouble is electron/electron#20027

I believe I have a workaround (based on  electron/electron#20970) but it needs more testing. Many members of the Scratch Team are taking vacation this week and/or next week, so we'll take another look at this in early January.
